package ibf2022.ssf.day16.controllers;

import java.util.Date;

import org.apache.catalina.connector.Response;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.json.Json;
import jakarta.json.JsonObject;

@RestController
// application/json
@RequestMapping(path = "/time", produces = MediaType.APPLICATION_JSON_VALUE)
public class TimeController {

    // GET /time
    // Accept: application/json
    // Response
    // < 200 OK
    // < Content-Type: appplication/json
    // < {"time": "the time"}

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> getTime() {
        String time = (new Date()).toString();
        JsonObject payload = Json.createObjectBuilder().add("time", time)
                .build();
        return ResponseEntity.ok(payload.toString());
    }

    // text/plain
    @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
    public ResponseEntity<String> getTimeAsText() {
        String time = (new Date()).toString();
        return ResponseEntity.ok("The current time/ date is %s".formatted(time));
    }

    // text/html
    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    public ResponseEntity<String> getTimeAsHTML() {
        String time = (new Date()).toString();
        return ResponseEntity.ok("<h1> The current time/date is %s</h1>".formatted(time));
        // ResponseEntity.status(200).header("X-Generated by")
    }
}
